version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: EST
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 10
    reviewers:
      - aferd
      - epwinchell
      - InsaneZein
      - nicolethoen
      - dlabaj

  - package-ecosystem: npm
    directory: "/packages/module"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: EST
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 10
    reviewers:
      - aferd
      - epwinchell
      - InsaneZein
      - nicolethoen
      - dlabaj
